#define NO_SIDE -1
#define EAST_SIDE 0
#define WEST_SIDE 1
#define INDEP_SIDE 2
#define CIV_SIDE 3
#define NEUTRAL_SIDE 4
#define ENEMY_SIDE 5
#define FRIENDLY_SIDE 6
#define LOGIC_SIDE 7

if (isServer) then {

_magazines = [
    "30Rnd_556x45_Stanag",
    "30Rnd_556x45_Stanag_Tracer_Red",
    "20Rnd_556x45_UW_mag",
    "30Rnd_65x39_caseless_mag",
    "30Rnd_65x39_caseless_mag_Tracer", //RED
    "20Rnd_762x51_Mag",
    "7Rnd_408_Mag",
    "5Rnd_127x108_Mag",
    "100Rnd_65x39_caseless_mag",
    "100Rnd_65x39_caseless_mag_Tracer",
    "NLAW_F",
    "1Rnd_HE_Grenade_shell",
    "1Rnd_Smoke_Grenade_shell",
    "1Rnd_SmokeRed_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeYellow_Grenade_shell",
    "1Rnd_SmokePurple_Grenade_shell",
    "1Rnd_SmokeBlue_Grenade_shell",
    "1Rnd_SmokeOrange_Grenade_shell",
    "HandGrenade",
    "MiniGrenade",
    "SmokeShell",
    "SmokeShellRed",
    "SmokeShellGreen",
    "SmokeShellYellow",
    "SmokeShellPurple",
    "SmokeShellBlue",
    "SmokeShellOrange",
    "Chemlight_green",
    "Chemlight_red",
    "Chemlight_yellow",
    "Chemlight_blue",
    "UGL_FlareWhite_F",
    "UGL_FlareGreen_F",
    "UGL_FlareRed_F",
    "UGL_FlareYellow_F",
    "UGL_FlareCIR_F",
    "FlareWhite_F",
    "FlareGreen_F",
    "FlareRed_F",
    "FlareYellow_F",
    "Laserbatteries",
    "Titan_AA",
    "Titan_AP",
    "Titan_AT",
    "11Rnd_45ACP_Mag",
    "6Rnd_45ACP_Cylinder",
    "10Rnd_762x51_Mag",
    "5Rnd_127x108_APDS_Mag",
    "B_IR_Grenade",
    "ATMine_Range_Mag",
    "APERSMine_Range_Mag",
    "APERSBoundingMine_Range_Mag",
    "SLAMDirectionalMine_Wire_Mag",
    "APERSTripMine_Wire_Mag",
    "ClaymoreDirectionalMine_Remote_Mag",
    "SatchelCharge_Remote_Mag",
    "DemoCharge_Remote_Mag",
    "AGM_PreloadedMissileDummy",
    "AGM_HandFlare_White",
    "AGM_HandFlare_Red",
    "AGM_HandFlare_Green",
    "AGM_HandFlare_Yellow",
    "AGM_M84", //FLASHBANG/STUN. 
    "CUP_Stinger_M",
    "CUP_17Rnd_9x19_glock17",
    "CUP_6Rnd_HE_M203",
    "CUP_6Rnd_FlareWhite_M203",
    "CUP_6Rnd_FlareGreen_M203",
    "CUP_6Rnd_FlareRed_M203",
    "CUP_6Rnd_FlareYellow_M203",
    "CUP_6Rnd_Smoke_M203",
    "CUP_6Rnd_SmokeRed_M203",
    "CUP_6Rnd_SmokeGreen_M203",
    "CUP_6Rnd_SmokeYellow_M203",
    "CUP_HandGrenade_M67",
    "CUP_HandGrenade_L109A1_HE",
    "CUP_HandGrenade_L109A2_HE",
    "CUP_Javelin_M",
    "CUP_M136_M",
    "CUP_Dragon_EP1_M",
    "CUP_MAAWS_HEDP_M",
    "CUP_MAAWS_HEAT_M",
    "CUP_30Rnd_9x19_MP5",
    "CUP_SMAW_HEDP_M_N",
    "CUP_SMAW_HEAA_M_N",
    "CUP_SMAW_HEDP_M",
    "CUP_SMAW_HEAA_M",
    "XLA_DUMMY"
];

_backpacks = [
    "AGM_NonSteerableParachute",
    "B_AA_01_weapon_F",
    "B_AssaulPack_blk",
    "B_AssaulPack_cbr",
    "B_AssaulPack_mcamo",
    "B_AssaulPack_rgr",
    "B_AssaulPack_sgg",
    "B_AT_01_weapon_F",
    "B_Carryall_cbr",
    "B_Carryall_khk",
    "B_Carryall_mcamo",
    "B_Carryall_oli",
    "B_GMG_01_A_high_weapon_F",
    "B_GMG_01_A_weapon_F",
    "B_GMG_01_high_weapon_F",
    "B_GMG_01_weapon_F",
    "B_HMG_01_A_high_weapon_F",
    "B_HMG_01_A_weapon_F",
    "B_HMG_01_high_weapon_F",
    "B_HMG_01_support_F",
    "B_HMG_01_support_high_F",
    "B_HMG_01_weapon_F",
    "B_Kitbag_cbr",
    "B_Kitbag_mcamo",
    "B_Kitbag_rgr",
    "B_Kitbag_sgg",
    "B_Mortar_01_support_F",
    "B_Mortar_01_weapon_F",
    "B_Parachute",
    "B_TacticalPack_blk",
    "B_TacticalPack_mcamo",
    "B_TacticalPack_oli",
    "B_TacticalPack_rgr",
    "B_UAV_01_backpack_F",   
    "STKR_MLode",
    "STKR_PackCom",
    "STKR_Predator",
    "STKR_PredatorBow",
    "tf_anarc210",  
    "tf_rt1523g_big",
    "tf_rt1523g_big_bwmod",
    "tf_rt1523g_big_rhs",
    "tf_rt1523g_black",    
    "tf_rt1523g_fabric",
    "tf_rt1523g_green",  
    "tf_rt1523g_sage"
];

//"CfgWeapons",
_weapons = [
    "CUP_optic_SUSAT",
    "acc_flashlight",
    "acc_pointer_IR",
    "AGM_Altimeter",
    "AGM_Bandage",
    "AGM_Bloodbag",   
    "AGM_CableTie",
    "AGM_Clacker",
    "AGM_DeadManSwitch",
    "AGM_DefusalKit",
    "AGM_EarBuds",    
    "AGM_Epipen",
    "AGM_ExplosiveItem",
    "AGM_IR_Strobe_Item",
    "AGM_ItemCore",
    "AGM_ItemKestrel",   
    "AGM_M26_Clacker",
    "AGM_MapTools",
    "AGM_Morphine",
    "AGM_muzzle_mzls_B",
    "AGM_muzzle_mzls_H",
    "AGM_muzzle_mzls_L",
    "AGM_NVG_Gen4",
    "AGM_NVG_Wide",
    "AGM_SpareBarrel",
    "AGM_UAVBattery",
    "AGM_Vector",
    "ALIVE_Tablet",
    "arifle_mas_l119",
    "arifle_mas_l119_d",
    "arifle_mas_l119_gl",
    "arifle_mas_l119_gl_d",
    "arifle_mas_l119_gl_v",
    "arifle_mas_l119_m203",
    "arifle_mas_l119_m203_v",
    "arifle_mas_l119_v",
    "arifle_mas_l119c",
    "arifle_mas_l119c_d",
    "arifle_mas_l119c_v",
    "arifle_SDAR_F", 
    "B_P_Beret",
    "B_P_BeretOff",
    "B_P_Beretpwrr",
    "B_P_Beretramc",
    "B_P_Beretramcoff",
    "B_P_BeretRct",
    "B_P_Beretrlc",
    "B_UavTerminal",
    "Binocular",
    "BinocularItem",
    "CUP_acc_Glock17_Flashlight",
    "CUP_arifle_L85A2",
    "CUP_arifle_L85A2_GL",
    "CUP_arifle_L86A2",
    "CUP_arifle_L85A2_Holo_laser",
    "CUP_arifle_L85A2_GL_Holo_Laser",
    "CUP_arifle_L85A2_SUSAT_Laser",
    "CUP_arifle_L85A2_GL_SUSAT_Laser",
    "CUP_arifle_L85A2_CWS_Laser",
    "CUP_arifle_L85A2_ACOG_Laser",
    "CUP_arifle_L85A2_GL_ACOG_Laser",
    "CUP_arifle_L86A2_ACOG",
    "CUP_Binocular_Vector",
    "CUP_glaunch_M32",
    "CUP_hgun_Glock17",
    "CUP_Laserdesignator",
    "CUP_launch_FIM92Stinger",  
    "CUP_launch_Javelin",
    "CUP_launch_M47",
    "CUP_launch_Mk153Mod0",
    "CUP_lmg_L110A1",
    "CUP_lmg_L7A2",   
    "CUP_muzzle_snds_AWM",
    "CUP_muzzle_snds_L85",
    "CUP_optic_ACOG",
    "CUP_optic_AN_PAS_13c1",
    "CUP_optic_AN_PAS_13c2",
    "CUP_optic_AN_PVS_10",
    "CUP_optic_AN_PVS_4",
    "CUP_optic_CompM2_Black",
    "CUP_optic_CompM4",
    "CUP_optic_CWS",
    "CUP_optic_ELCAN_SpecterDR",
    "CUP_optic_ElcanM145",
    "CUP_optic_Leupold_VX3",
    "CUP_optic_LeupoldM3LR",
    "CUP_optic_LeupoldMk4",
    "CUP_optic_LeupoldMk4_10x40_LRT_Desert",
    "CUP_optic_LeupoldMk4_10x40_LRT_Woodland",
    "CUP_optic_LeupoldMk4_CQ_T",
    "CUP_optic_LeupoldMk4_MRT_tan",
    "CUP_optic_MAAWS_Scope",
    "CUP_optic_MRad",
    "CUP_optic_RCO",
    "CUP_optic_SB_11_4x20_PM",
    "CUP_optic_SB_3_12x50_PMII",
    "CUP_optic_SMAW_Scope",
    "CUP_optic_TrijiconRx01_black",
    "CUP_optic_TrijiconRx01_desert",
    "CUP_optic_ZDDot",
    "CUP_sgun_M1014", //shotgun
    "CUP_smg_MP5A5",
    "CUP_smg_MP5SD6",
    "CUP_srifle_AS50",
    "CUP_srifle_AWM_des",
    "CUP_srifle_AWM_wdl",
    "CUP_Vector21Nite",
    "GoggleItem",
    "H_Booniehat_grn",
    "H_Booniehat_khk",
    "H_Booniehat_mcamo",   
    "H_Booniehat_oli",
    "H_Booniehat_tan",     
    "H_Cap_blk",    
    "H_Cap_grn",
    "H_Cap_headphones",  
    "H_Cap_oli",
    "H_Cap_tan",
    "H_CrewHelmetHeli_B",   
    "H_HelmetCrew_I", //technically AAF, but most "real" looking crew helmet
    "H_MilCap_gry",
    "H_MilCap_mcamo",
    "H_PilotHelmetFighter_B",
    "H_Watchcap_blk",  
    "Headgear_H_HelmetCrew_I",
    "ItemCompass",
    "ItemGPS",
    "ItemMap",
    "ItemWatch",
    "Laserdesignator",
    "launch_B_Titan_F",
    "launch_B_Titan_short_F",
    "launch_NLAW_F",
    "launch_Titan_F",
    "launch_Titan_short_F",   
    "MineDetector",
    "muzzle_mas_snds_M",
    "muzzle_mas_snds_Mc",
    "muzzle_snds_acp",    
    "muzzle_snds_B",
    "muzzle_snds_H",
    "muzzle_snds_H_MG",
    "muzzle_snds_H_SW",
    "muzzle_snds_L",
    "muzzle_snds_M",
    "NVGoggles",
    "NVGoggles_INDEP",
    "NVGoggles_OPFOR",
    "optic_Aco",
    "optic_Arco",
    "optic_DMS",
    "optic_Hamr",
    "optic_Holosight",
    "optic_LRPS",
    "optic_mas_acog",
    "optic_mas_acog_eo",
    "optic_mas_aim",
    "optic_mas_DMS",
    "optic_mas_handle",
    "optic_mas_term",
    "optic_MRCO",
    "optic_Nightstalker",
    "optic_NVS",
    "optic_SOS",
    "optic_tws",
    "optic_tws_mg",
    "RadioItem",
    "Rangefinder",
    "ScubaItem",
    "STKR_HMNVS",
    "STKR_L129A1",
    "STKR_L129A1_ACOG",
    "STKR_L129A1_Bipod",
    "STKR_L129A1_HG",
    "STKR_L129A1_HG_Bipod", 
    "STKR_MK7",
    "STKR_MK7_Scrim",
    "STKR_MK7_ScrimB",
    "STKR_Osprey_G",
    "STKR_Osprey_MG",
    "STKR_Osprey_R",
    "STKR_Osprey_SL",
    "TabletItem",
    "tf_anprc152",
    "tf_microdagr",
    "tf_rf7800str",
    "ToolKit",
    "ToolKitItem",
    "U_B_GhillieSuit",
    "U_B_PilotCoveralls",
    "U_B_survival_uniform",    
    "U_B_Wetsuit",
    "UK3CB_BAF_Helmet_HeliPilot_RN",
    "UK3CB_BAF_Uniform_HeliPilot_RN",
    "UK3CB_BAF_Uniform_MTP",
    "UK3CB_BAF_Uniform_MTP_ShortSleeve",
    "UK3CB_CUP_arifle_L85A2_GL_LDS_Laser",
    "UK3CB_CUP_arifle_L85A2_LDS_Laser",
    "UK3CB_CUP_arifle_L86A2_LDS",
    "UK3CB_CUP_lmg_L110A1_ACOG",
    "UK3CB_CUP_lmg_L110A1_LDS",
    "UK3CB_CUP_lmg_L7A2_LDS",
    "UK3CB_STKR_L129A1_Bipod_LDS",
    "UK3CB_STKR_L129A1_Bipod_PMII",
    "V_PlateCarrier1_blk",
    "V_PlateCarrierH_CTRG",
    "V_PlateCarrierL_CTRG",
    "V_RebreatherB",
    "V_TacVest_blk",
    "V_TacVest_camo",
    "V_TacVest_khk",
    "V_TacVest_oli",
    "V_TacVestIR_blk"
];

_glasses = [
    "None",
    "G_Combat",
    "G_Lowprofile",
    "G_Shades_Black",   
    "G_Tactical_Black",
    "G_Aviator",
    "G_Diving",
    "G_B_Diving",
    "G_Goggles_clear",
    "G_Balaclava_blk",
    "G_Balaclava_oli",
    "G_Balaclava_combat",
    "G_Balaclava_lowprofile",
    "G_Bandanna_blk",
    "G_Bandanna_oli",
    "G_Bandanna_khk",
    "G_Bandanna_tan",
    "G_Bandanna_shades",
    "G_Bandanna_sport",
    "G_Bandanna_aviator",
    "G_Tactical_Clear"
];



    // Grab the parameter that was passed in. 
    // The box should have "this execVM <scriptname>" in it's init field.
    _box = [_this, 0, objNull, [objNull]] call BIS_fnc_param;






    // Check if @XLA_FixedArsenal is loaded
     if (isnil "XLA_fnc_addVirtualItemCargo") then {

        hint "@XLA_FixedArsenal not found.";

    } else {    

        [_box, _weapons + _glasses,true,false] call XLA_fnc_addVirtualItemCargo; 
        [_box, _weapons,true,false] call XLA_fnc_addVirtualWeaponCargo; 
        [_box, _backpacks ,true,false] call XLA_fnc_addVirtualBackpackCargo; 
        [_box, _magazines ,true,false] call XLA_fnc_addVirtualMagazineCargo; 
        
        // Start the arsenal on it
        _addActionText = "<t color='#45B6EA'>Open Armoury (core/fast)";
        ["AmmoboxInit",[_box,false,{true},_addActionText,false]] spawn XLA_fnc_arsenal;


    };
};
